<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.11.0 on darwin)" generated="2025-03-20T08:19:06.987291" rpa="false" schemaversion="5">
<suite id="s1" name="Tests" source="/Users/mitran/pythonProject/RobotFramework/tests">
<suite id="s1-s1" name="Testdemo5" source="/Users/mitran/pythonProject/RobotFramework/tests/testdemo5.robot">
<test id="s1-s1-t1" name="Validate login unsuccessfully with invalid credentials" line="17">
<status status="FAIL" start="2025-03-20T08:19:07.303138" elapsed="0.001131">Test cannot be empty.</status>
</test>
<doc>To validate the Login form</doc>
<status status="FAIL" start="2025-03-20T08:19:07.033792" elapsed="0.271657"/>
</suite>
<status status="FAIL" start="2025-03-20T08:19:07.003098" elapsed="0.303307"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Tests" id="s1" pass="0" fail="1" skip="0">Tests</stat>
<stat name="Testdemo5" id="s1-s1" pass="0" fail="1" skip="0">Tests.Testdemo5</stat>
</suite>
</statistics>
<errors>
<msg time="2025-03-20T08:19:07.299747" level="ERROR">[ DataDriver ] Error in robot file:
  File "/Users/mitran/pythonProject/RobotFramework/tests/testdemo5.robot", line 0</msg>
<msg time="2025-03-20T08:19:07.299959" level="ERROR">In source file:
  File "resources/data.csv", line 0</msg>
<msg time="2025-03-20T08:19:07.302902" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ValueError: Unassigned requiered argument detected: ${username}.</msg>
</errors>
</robot>
